name: Teste de Segredos
on: [push]

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar se existe
        run: |
          if [ -z "${{ secrets.REMOTE_HOST }}" ]; then
            echo "ERRO: REMOTE_HOST está vazio!"
            exit 1
          else
            echo "SUCESSO: REMOTE_HOST foi encontrado (o valor está mascarado pelo GitHub)."
          fi
