name: Deploy to VPS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Deploy to Server"
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: "riboli.cloud"
        username: "eriboli@github"
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /projects/cad_users/BackEnd
          npm i
          git pull
          pm2 restart 0
